# This is for dev
version: '3.7'

services:
  api:
    build:
      context: .
      target: dev
    container_name: task-api
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      TZ: Europe/Paris
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    build: task-db
    container_name: task-db
    environment:
      TZ: Europe/Paris
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=en_US.UTF-8'
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db:
